### ISSUE TITLE
Index sorting has an error when using date as the target field at v0.20.2

### ISSUE THREAD

**Issue by PeterDing** [quickwit-inc/tantivy#2164] opened 2023-08-30 11:25 UTC
**Describe the bug**

I followed the [index sorting doc](https://github.com/quickwit-oss/tantivy/blob/main/doc/src/index_sorting.md) to use `IndexSettings` to sort the target field (Date) at `v0.20.2`. I got an error as following:

```
thread 'thrd-tantivy-index0' panicked at /home/peter/.cargo/registry/src/index.crates.io-6f17d22bba15001f/tantivy-0.20.2/src/indexer/doc_id_mapping.rs:94:31:
index out of bounds: the len is 0 but the index is 0
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
Error: ErrorInThread("Any { .. }")
```

But, with the version `v0.19.2` the error is gone.

**Which version of tantivy are you using?**

Demo code was running at `tantivy = "0.20.2"`.

**To Reproduce**

The demo code is:

- Cargo.toml
```toml
[package]
name = "test-tantivy"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
tantivy = "0.20.2"
indicatif = "0.17"
```

- main.rs
```rust
use indicatif::ProgressBar;
use tantivy::directory::MmapDirectory;
use tantivy::schema::*;
use tantivy::DateTime;
use tantivy::Directory;
use tantivy::Index;
use tantivy::IndexSettings;
use tantivy::IndexSortByField;
use tantivy::Order;

fn main() -> tantivy::Result<()> {
    let index_path = "./index";

    let mut schema_builder = Schema::builder();
    schema_builder.add_date_field("date", INDEXED | FAST | STORED);

    let index_settings = IndexSettings {
        sort_by_field: Some(IndexSortByField {
            field: "date".to_owned(), // Sort by date
            order: Order::Asc,
        }),
        ..Default::default()
    };

    let schema = schema_builder.build();

    let mmap_directory: Box<dyn Directory> = Box::new(MmapDirectory::open(index_path).unwrap());

    let index = Index::builder()
        .schema(schema.clone())
        .settings(index_settings)
        .open_or_create(mmap_directory)?;

    let mut index_writer = index.writer(50_000_000)?;

    let date = schema.get_field("date").unwrap();

    let n = 100;
    let bar = ProgressBar::new(n).with_style(
        indicatif::ProgressStyle::default_bar()
            .template(
                "{spinner:.green} {elapsed}/{eta} [{bar:40.cyan/blue}] {pos:>7}/{len:7} {msg}",
            )
            .unwrap()
            .progress_chars("#>-"),
    );

    for i in 0..n {
        let mut doc = Document::default();
        doc.add_date(date, DateTime::from_timestamp_secs(i as i64));
        index_writer.add_document(doc)?;
        bar.inc(1);
    }
    bar.finish();

    index_writer.commit()?;

    Ok(())
}
```

**Comment by PSeitz** [comment] 2023-08-30 12:57
This is a duplicate of https://github.com/quickwit-oss/tantivy/issues/2112 and has been fixed https://github.com/quickwit-oss/tantivy/pull/2124 but not yet been released

**Closed as completed** 2023-09-05 07:20 UTC
